language: android
android:
  components:
    - tools # to get the new `repository-11.xml`
    - tools # see https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943)
    - platform-tools
    - build-tools-26.0.1
    - build-tools-26.0.2
    - android-26
    - extra-android-support
licenses:
  - 'android-sdk-license-.+'
  - '.+'
script:
  - ./gradlew build
  - ./gradlew test
  - ./gradlew ExampleUnitTest
before_install:
  - cd Songle
  - chmod +x gradlew